import json

class Maps:
  name_map = {
    'V': 'Voltage',
    'V2': 'Voltage CH2',
    'V3': 'Voltage CH3',
    'VS': 'Voltage Starter',
    'VM': 'Voltage Mid-Point',
    'DM': 'Deviation Mid-Point',
    'VPV': 'Voltage Panel',
    'PPV': 'Power Panel',
    'I': 'Current',
    'I2': 'Current CH2',
    'I3': 'Current CH3',
    'IL': 'Current Load',
    'LOAD': 'Load State',
    'T': 'Temperature',
    'P': 'Power',
    'CE': 'Consumed Amp Hours',
    'SOC': 'State-of-charge',
    'TTG': 'Time-to-go',
    'Alarm': 'Alarm',
    'Relay': 'Relay State',
    'AR': 'Alarm reason',
    'OR': 'Off reason',
    'H1': 'Depth of the deepest discharge',
    'H2': 'Depth of the last discharge',
    'H3': 'Depth of the average discharge',
    'H4': 'Number of charge cycles',
    'H5': 'Number of full discharges',
    'H6': 'Cumulative Amp Hours drawn',
    'H7': 'Minimum main (battery) voltage',
    'H8': 'Maximum main (battery) voltage',
    'H9': 'Number of seconds since last full charge',
    'H10': 'Number of automatic synchronizations',
    'H11': 'Number of low main voltage alarms',
    'H12': 'Number of high main voltage alarms',
    'H13': 'Number of low auxiliary voltage alarms',
    'H14': 'Number of high auxiliary voltage alarms',
    'H15': 'Minimum auxiliary (battery) voltage',
    'H16': 'Maximum auxiliary (battery) voltage',
    'H17': 'Amount of discharged energy/produced Energy',
    'H18': 'Amount of charged energy/consumed Energy',
    'H19': 'Yield total',
    'H20': 'Yield today',
    'H21': 'Max Power today',
    'H22': 'Yield yesterday',
    'H23': 'Max Power yesterday',
    'ERR': 'Error code',
    'CS': 'Operation State',
    'BMV': 'Model description',
    'FW': 'Firmware version',
    'FWE': 'Firmware version',
    'PID': 'Product ID',
    'SER#': 'Serial number',
    'HSDS': 'Day sequence number',
    'MODE': 'Device Mode',
    'AC_OUT_V': 'Voltage AC Output',
    'AC_OUT_I': 'Current AC Output',
    'AC_OUT_S': 'Power AC Output',
    'WARN': 'Warning reason',
    'MPPT': 'Tracker Operation mode',
    'MON': 'DC monitor mode',
    'DC_IN_V': 'Voltage DC Input',
    'DC_IN_I': 'Current DC Input',
    'DC_IN_P': 'Power DC Input'
  }

  measurement_map={
    'V': 'mV', 
    'V2': 'mV', 
    'V3': 'mV', 
    'VS': 'mV', 
    'VM': 'mV', 
    'DM': '‰', 
    'VPV': 'mV', 
    'PPV': 'W', 
    'I': 'mA', 
    'I2': 'mA', 
    'I3': 'mA', 
    'IL': 'mA', 
    'LOAD': 'on/off', 
    'T': 'C', 
    'P': 'W', 
    'CE': 'mAh', 
    'SOC': '‰', 
    'TTG': 'Minutes', 
    'Alarm': 'on/off', 
    'Relay': 'on/off', 
    'AR': 'text_map', 
    'OR': 'text_map', 
    'H1': 'mAh', 
    'H2': 'mAh', 
    'H3': 'mAh', 
    'H4': 'total', 
    'H5': 'total', 
    'H6': 'mAh', 
    'H7': 'mV', 
    'H8': 'mV', 
    'H9': 'Seconds', 
    'H10': 'total', 
    'H11': 'total',
    'H12': 'total', 
    'H13': 'total', 
    'H14': 'total', 
    'H15': 'mV', 
    'H16': 'mV', 
    'H17': '0.01 kWh', 
    'H18': '0.01 kWh', 
    'H19': '0.01 kWh', 
    'H20': '0.01 kWh', 
    'H21': 'W', 
    'H22': '0.01 kWh', 
    'H23': 'W', 
    'ERR': 'text_map', 
    'CS': 'text_map', 
    'BMV': 'text', 
    'FW': 'text', 
    'FWE': 'text', 
    'PID': 'text', 
    'SER#': 'text', 
    'HSDS': 'total', 
    'MODE': 'text_map', 
    'AC_OUT_V': '0.01 V', 
    'AC_OUT_I': '0.1 A', 
    'AC_OUT_S': 'VA', 
    'WARN': '', #TODO
    'MPPT': 'text_map', 
    'MON': 'text_map', 
    'DC_IN_V': '0.01 V', 
    'DC_IN_I': 'A', 
    'DC_IN_P': 'W', 
  }

  text_maps={
    'AR': {
      '0': '--',
      '1': 'Low Voltage',
      '2': 'High Voltage',
      '4': 'Low SOC',
      '8':'Low Starter Voltage',
      '16':'High Starter Voltage',
      '32':'Low Temperature',
      '64':'High Temperature',
      '128':'Mid Voltage',
      '256':'Overload',
      '512':'DC-ripple',
      '1024':'Low V AC out',
      '2048':'High V AC out',
      '4096':'Short Circuit',
      '8192':'BMS Lockout',
    },
    'OR': {
      '0x00000001': 'No input power',
      '0x00000002': 'Switched off (power switch)',
      '0x00000004': 'Switched off (device mode register)',
      '0x00000008': 'Remote input',
      '0x00000010': 'Protection active',
      '0x00000020': 'Paygo',
      '0x00000040': 'BMS',
      '0x00000080': 'Engine shutdown detection',
      '0x00000100': 'Analysing input voltage'
    },
    'CS': {
      '0': 'Off',
      '1': 'Low power',
      '2': 'Fault',
      '3': 'Bulk',
      '4': 'Absorption',
      '5': 'Float',
      '6': 'Storage',
      '7': 'Equalize (manual)',
      '9': 'Inverting',
      '11': 'Power supply',
      '245': 'Starting-up',
      '246': 'Repeated absorption',
      '247': 'Auto equalize / Recondition',
      '248': 'BatterySafe',
      '252': 'External Control',
    },
    'ERR': {
      '0': 'No error',
      '2': 'Battery voltage too high',
      '17': 'Charger temperature too high',
      '18': 'Charger over current',
      '19': 'Charger current reversed',
      '20': 'Bulk time limit exceeded',
      '21': 'Current sensor issue (sensor bias/sensor broken)',
      '26': 'Terminals overheated',
      '28': 'Converter issue (dual converter models only)',
      '33': 'Input voltage too high (solar panel)',
      '34': 'Input current too high (solar panel)',
      '38': 'Input shutdown (due to excessive battery voltage)',
      '39': 'Input shutdown (due to current flow during off mode)',
      '65': 'Lost communication with one of devices',
      '66': 'Synchronised charging device configuration issue',
      '67': 'BMS connection lost',
      '68': 'Network misconfigured',
      '116': 'Factory calibration data lost',
      '117': 'Invalid/incompatible firmware',
      '119': 'User settings invalid'
    },
    'MODE': {
      '1': 'VE_REG_MODE_CHARGER',
      '2': 'VE_REG_MODE_INVERTER',
      '4': 'VE_REG_MODE_OFF',
      '5': 'VE_REG_MODE_ECO',
      '253': 'VE_REG_MODE_HIBERNATE',
    },
    'MPPT': {
      '0': 'Off',
      '1': 'Voltage or current limited',
      '2': 'MPP Tracker active'
    },
    'MON':{
      '-9': 'Solar charger',
      '-8': 'Wind turbine',
      '-7': 'Shaft generator',
      '-6': 'Alternator',
      '-5': 'Fuel cell',
      '-4': 'Water generator',
      '-3': 'DC/DC charger',
      '-2': 'AC charger',
      '-1': 'Generic source',
      '0': 'Battery monitor (BMV)',
      '1': 'Generic load',
      '2': 'Electric drive',
      '3': 'Fridge',
      '4': 'Water pump',
      '5': 'Bilge pump',
      '6': 'DC system',
      '7': 'Inverter',
      '8': 'Water heater'
    }
  }